revert aws sdk version from 076f4c20742bc6d25f919579a2790a9c97c08f89 (#18695)
Due to failures in migration:

```
2024-11-19 17:16:15.916	picocli.CommandLine$ExecutionException: Error while calling command (public java.lang.Integer org.openmetadata.service.util.OpenMetadataOperations.migrate(boolean)): java.lang.NoClassDefFoundError: software/amazon/awssdk/checksums/SdkChecksum
2024-11-19 17:16:15.641	Updating bot users in case of an update on the JSON schema: [managed-aws]
2024-11-19 17:16:14.903	Updating services in case of an update on the JSON schema: [managed-aws]
```